# prompt_bank.py
"""
Reusable prompt bank and perspective suffixes.

Provides:
- PHASE1_FAMILIES: dict of neutral prompt families for Phase 1.
- CS/Lit/Neutral suffixes.
- BASE_QUESTIONS_MANY for corridor-style experiments.
"""

CS_SUFFIX = "Answer from a computer science perspective."
LIT_SUFFIX = "Answer from a literature and arts perspective."
NEUTRAL_SUFFIX = "Give a detailed, thoughtful answer."

# ---- Phase 1 neutral families (>= 20 prompts total) ----

# ---- Phase 1 neutral families (50 prompts per category) ----

PROMPTS_GENERAL_QA_NEUTRAL = [
    # Originals
    "Why do people form communities?",
    "How does technology change how we think about ourselves?",
    "Why do some people enjoy taking risks while others avoid them?",
    "How do habits shape a person's long-term identity?",
    "Why do people sometimes act against their own long-term interests?",
    # Expansion
    "How does language influence the way we perceive the world?",
    "Why do cultures develop different social norms regarding personal space?",
    "What role does nostalgia play in shaping our current decisions?",
    "How does the concept of privacy change in the digital age?",
    "Why is storytelling a fundamental part of human communication?",
    "How do hierarchies naturally emerge in social groups?",
    "Why do people often fear the unknown more than known dangers?",
    "What constitutes a 'fair' society in modern terms?",
    "How does architecture influence the behavior of people in a city?",
    "Why do we seek validation from peers?",
    "How does the perception of time change as we age?",
    "What is the psychological function of humor?",
    "Why do certain traditions survive for centuries while others fade?",
    "How does mentorship benefit both the mentor and the mentee?",
    "Why is adaptability considered a key survival trait?",
    "How does stress affect decision-making processes?",
    "What is the relationship between creativity and boredom?",
    "Why do people volunteer their time without financial reward?",
    "How does consumerism affect personal happiness?",
    "Why do we feel empathy for fictional characters?",
    "How does the physical environment impact mental well-being?",
    "Why is trust essential for economic systems to function?",
    "How do educational systems shape a society's values?",
    "Why do people resist changing their minds even when presented with facts?",
    "What defines the difference between knowledge and wisdom?",
    "How does sleep affect cognitive performance?",
    "Why do fashions and trends cycle over time?",
    "How does competition drive innovation?",
    "Why is silence important in communication?",
    "How do shared rituals strengthen group cohesion?",
    "What is the role of failure in the learning process?",
    "Why do we tend to remember negative events more vividly than positive ones?",
    "How does music affect human emotion?",
    "Why is curiosity important for scientific progress?",
    "How does the concept of 'work' vary across different cultures?",
    "Why do humans seek to explore outer space?",
    "How does reading fiction improve social intelligence?",
    "Why is forgiveness often difficult to grant?",
    "How does urbanization change family structures?",
    "Why do we procrastinate on important tasks?",
    "How does diet impact physical and mental health?",
    "Why is biodiversity important for a stable ecosystem?",
    "How do social media algorithms influence public discourse?",
    "Why is preserving history important for future generations?",
    "How does discipline differ from motivation?",
]

PROMPTS_GSM8K_STYLE_NEUTRAL = [
    # Originals
    "A shop sells pencils for 3 dollars each. If Maria buys 4 pencils and then returns 1, how much does she spend in total?",
    "A farmer has 12 chickens and buys 7 more. If 5 chickens are sold later, how many chickens remain on the farm?",
    "A teacher has 30 stickers. She gives 4 stickers to each of 5 students. How many stickers does she have left?",
    "A box holds 8 books. If there are 5 boxes and 6 books are removed from the last box, how many books remain in all boxes?",
    "A train can carry 120 passengers in one trip. If it makes 3 trips and 45 seats are empty on the last trip, how many passengers were carried?",
    # Expansion
    "A baker bakes 20 loaves of bread in the morning and 15 in the afternoon. If he sells 32 loaves by evening, how many are left?",
    "Jenny has 50 dollars. She buys a shirt for 20 dollars and a hat for 15 dollars. How much money does she have remaining?",
    "A library has 5 shelves. Each shelf holds 40 books. If 30 books are checked out, how many books are still on the shelves?",
    "A runner runs 5 miles on Monday, 3 miles on Tuesday, and 6 miles on Wednesday. What is the total distance run over the three days?",
    "A fruit basket contains 10 apples and 8 oranges. If 3 apples and 2 oranges are eaten, how many pieces of fruit remain?",
    "A movie theater has 200 seats. If 120 tickets are sold for the early show and 150 for the late show, how many empty seats were there in total across both shows?",
    "Tom collects stamps. He starts with 100 stamps, buys 25 more, and then gives 10 to a friend. How many stamps does he have now?",
    "A parking lot has 4 rows of spaces. Each row has 15 spaces. If 40 cars represent the current occupancy, how many empty spaces are there?",
    "A gardener plants 6 rows of carrots with 8 carrots in each row. Rabbits eat 5 carrots. How many carrots are left?",
    "A tank holds 500 gallons of water. If 50 gallons are used daily for 4 days, how much water remains in the tank?",
    "A student studies for 45 minutes on Monday and 60 minutes on Tuesday. How many total minutes did the student study?",
    "A pack of cards has 52 cards. If 4 players are dealt 5 cards each, how many cards are left in the deck?",
    "A carpenter has 3 boards of wood, each 10 feet long. He cuts 2 feet off each board. What is the total length of the remaining wood?",
    "A cafe sells 100 coffees in the morning. In the afternoon, they sell half that amount. How many coffees did they sell in total?",
    "A jar contains 60 candies. If John takes 15 and Sarah takes 20, how many candies are left in the jar?",
    "A bus travels 100 miles. It stops after 40 miles and then travels another 30 miles. How many miles are left to go?",
    "A factory produces 500 widgets an hour. If the machine breaks down for 30 minutes, how many widgets are produced in that hour?",
    "A chef uses 3 eggs for every cake. If he wants to bake 6 cakes but drops 2 eggs, how many eggs does he need in total (including the dropped ones)?",
    "A building has 10 floors. Each floor has 4 apartments. If 5 apartments are vacant, how many actuaully have tenants?",
    "A cyclist travels at 15 miles per hour. How far does she travel in 3 hours?",
    "A phone battery lasts for 12 hours. If it has been used for 4 hours and then charged for 1 hour (adding 2 hours of life), how much life is left?",
    "A store has 50 red shirts and 30 blue shirts. If they sell 10 red and 5 blue, how many shirts are left in total?",
    "A rectangle has a length of 10 and a width of 5. If the length is doubled, what is the new perimeter?",
    "A pizza is cut into 8 slices. If 3 people eat 2 slices each, how many slices are left?",
    "A water bottle holds 2 liters. If you drink 500ml, how many ml are left?",
    "A notebook has 100 pages. If you use 5 pages a day for a week, how many pages are left?",
    "A zoo has 5 lions and 4 tigers. If 2 cubs are born to the lions, how many big cats are there in total?",
    "A worker earns 15 dollars an hour. If they work 8 hours a day for 5 days, how much do they earn?",
    "A rope is 20 meters long. It is cut into 4 equal pieces. How long is each piece?",
    "A computer costs 800 dollars. If it is on sale for 10 percent off, what is the new price?",
    "A jar of jellybeans has 30 red, 20 blue, and 10 green beans. If you remove all the green ones, how many are left?",
    "A car uses 1 gallon of gas for every 25 miles. How many gallons are needed for a 150-mile trip?",
    "A calendar has 30 days in a month. If 4 Sundays have passed, how many days are left in the month (assuming the 30th wasn't a Sunday)?",
    "A warehouse has 100 boxes. A truck takes 40 boxes, and another truck brings 20 new boxes. How many boxes are in the warehouse now?",
    "A music playlist has 10 songs. Each song is 3 minutes long. How long is the playlist in minutes?",
    "A swimmer does 10 laps in a pool. Each lap is 50 meters. How many meters did they swim?",
    "A cake requires 2 cups of sugar. If you make 3 cakes but spill half a cup, how much sugar did you use/waste total?",
    "A box of chocolates has 24 pieces. If 4 people share it equally, how many pieces does each person get?",
    "A tree grows 2 feet every year. If it is 10 feet tall now, how tall will it be in 5 years?",
    "A flight is 6 hours long. If 2 hours have passed, how many minutes are left?",
]

GSM8K_GOLD_ANSWERS = {
    PROMPTS_GSM8K_STYLE_NEUTRAL[0]: 9,
    PROMPTS_GSM8K_STYLE_NEUTRAL[1]: 14,
    PROMPTS_GSM8K_STYLE_NEUTRAL[2]: 10,
    PROMPTS_GSM8K_STYLE_NEUTRAL[3]: 34,
    PROMPTS_GSM8K_STYLE_NEUTRAL[4]: 315,
    PROMPTS_GSM8K_STYLE_NEUTRAL[5]: 3,
    PROMPTS_GSM8K_STYLE_NEUTRAL[6]: 15,
    PROMPTS_GSM8K_STYLE_NEUTRAL[7]: 170,
    PROMPTS_GSM8K_STYLE_NEUTRAL[8]: 14,
    PROMPTS_GSM8K_STYLE_NEUTRAL[9]: 13,
    PROMPTS_GSM8K_STYLE_NEUTRAL[10]: 130,
    PROMPTS_GSM8K_STYLE_NEUTRAL[11]: 115,
    PROMPTS_GSM8K_STYLE_NEUTRAL[12]: 20,
    PROMPTS_GSM8K_STYLE_NEUTRAL[13]: 43,
    PROMPTS_GSM8K_STYLE_NEUTRAL[14]: 300,
    PROMPTS_GSM8K_STYLE_NEUTRAL[15]: 105,
    PROMPTS_GSM8K_STYLE_NEUTRAL[16]: 32,
    PROMPTS_GSM8K_STYLE_NEUTRAL[17]: 24,
    PROMPTS_GSM8K_STYLE_NEUTRAL[18]: 150,
    PROMPTS_GSM8K_STYLE_NEUTRAL[19]: 25,
    PROMPTS_GSM8K_STYLE_NEUTRAL[20]: 30,
    PROMPTS_GSM8K_STYLE_NEUTRAL[21]: 250,
    PROMPTS_GSM8K_STYLE_NEUTRAL[22]: 20,
    PROMPTS_GSM8K_STYLE_NEUTRAL[23]: 35,
    PROMPTS_GSM8K_STYLE_NEUTRAL[24]: 45,
    PROMPTS_GSM8K_STYLE_NEUTRAL[25]: 10,
    PROMPTS_GSM8K_STYLE_NEUTRAL[26]: 65,
    PROMPTS_GSM8K_STYLE_NEUTRAL[27]: 50,
    PROMPTS_GSM8K_STYLE_NEUTRAL[28]: 2,
    PROMPTS_GSM8K_STYLE_NEUTRAL[29]: 1500,
    PROMPTS_GSM8K_STYLE_NEUTRAL[30]: 65,
    PROMPTS_GSM8K_STYLE_NEUTRAL[31]: 11,
    PROMPTS_GSM8K_STYLE_NEUTRAL[32]: 600,
    PROMPTS_GSM8K_STYLE_NEUTRAL[33]: 5,
    PROMPTS_GSM8K_STYLE_NEUTRAL[34]: 720,
    PROMPTS_GSM8K_STYLE_NEUTRAL[35]: 50,
    PROMPTS_GSM8K_STYLE_NEUTRAL[36]: 6,
    PROMPTS_GSM8K_STYLE_NEUTRAL[37]: 2,
    PROMPTS_GSM8K_STYLE_NEUTRAL[38]: 80,
    PROMPTS_GSM8K_STYLE_NEUTRAL[39]: 30,
    PROMPTS_GSM8K_STYLE_NEUTRAL[40]: 500,
    PROMPTS_GSM8K_STYLE_NEUTRAL[41]: 6.5,
    PROMPTS_GSM8K_STYLE_NEUTRAL[42]: 6,
    PROMPTS_GSM8K_STYLE_NEUTRAL[43]: 20,
    PROMPTS_GSM8K_STYLE_NEUTRAL[44]: 240,
}

PROMPTS_STORIES_NEUTRAL = [
    # Originals
    "Write a short scene where a person waits alone at a train station late at night.",
    "Describe a moment when someone realizes they have misunderstood a close friend.",
    "Write a short story about a traveler who returns to their hometown after many years away.",
    "Describe a conversation between two strangers who share an unexpected connection.",
    "Write a short scene where a character has to make a difficult but necessary decision.",
    # Expansion
    "Describe the atmosphere of a quiet library just before closing time.",
    "Write a story about a person discovering an old letter inside a used book.",
    "Describe a scene where a character tries to fix a broken mechanical watch.",
    "Write a short scene about two people stuck in an elevator for an hour.",
    "Describe the feeling of walking through a dense fog in the early morning.",
    "Write a story about a gardener who finds a plant they didn't plant.",
    "Describe a character's reaction to seeing the ocean for the first time.",
    "Write a scene where a group of friends gathers for a meal without their phones.",
    "Describe the sounds and smells of a busy street market at noon.",
    "Write a story about someone who decides to learn a difficult instrument late in life.",
    "Describe a moment where a character conquers a small, personal fear.",
    "Write a scene where a child tries to hide a stray animal in their room.",
    "Describe the interior of an antique shop filled with forgotten objects.",
    "Write a story about a photographer trying to capture the perfect sunrise.",
    "Describe a conversation between a mentor and a student about failure.",
    "Write a scene set in a kitchen while a family prepares a large holiday meal.",
    "Describe the view from a window during a heavy thunderstorm.",
    "Write a story about a person who finds a set of keys and tries to find the owner.",
    "Describe a character waking up in a tent in the middle of a forest.",
    "Write a scene where two rivals are forced to work together on a project.",
    "Describe the silence of a city street after a heavy snowfall.",
    "Write a story about someone receiving a package with no return address.",
    "Describe a character's attempt to bake a complicated cake for the first time.",
    "Write a scene where an astronaut looks back at Earth from a window.",
    "Describe the experience of running a marathon at the moment of hitting 'the wall'.",
    "Write a story about a character who decides to walk home instead of taking the bus.",
    "Describe the tension in a waiting room before a job interview.",
    "Write a scene where a character visits their childhood playground.",
    "Describe a long drive on an empty highway at sunset.",
    "Write a story about a person who discovers a secret room in their new house.",
    "Describe the interaction between a customer and a barista who knows their order.",
    "Write a scene where someone tries to assemble furniture without instructions.",
    "Describe the feeling of relief after finishing a long, difficult project.",
    "Write a story about a detective solving a crime involving a missing cat.",
    "Describe a character browsing through old vinyl records in a dusty store.",
    "Write a scene where a character has to apologize for a mistake they made.",
    "Describe the lights of a carnival seen from a distance at night.",
    "Write a story about a painter struggling to find the right shade of blue.",
    "Describe a character packing a suitcase for a trip with no return date.",
    "Write a scene where someone finds a time capsule buried in their backyard.",
    "Describe the noise and chaos of a school cafeteria during lunch.",
    "Write a story about a person who decides to disconnect from the internet for a week.",
    "Describe a character sitting on a park bench watching the seasons change.",
    "Write a scene where a musician plays a street performance for a small crowd.",
    "Describe the sensation of swimming in a cold lake on a hot day.",
]

PROMPTS_CODE_NEUTRAL = [
    # Originals
    "Write a Python function that returns the nth Fibonacci number using iteration.",
    "Write a Python function that checks if a string is a palindrome.",
    "Write a Python function that computes the sum of all numbers in a list.",
    "Write a Python function that reads a text file and counts how many lines it has.",
    "Write a Python function that sorts a list of integers using bubble sort.",
    # Expansion
    "Write a Python function to calculate the factorial of a number using recursion.",
    "Write a Python function that reverses the words in a given sentence.",
    "Write a Python function to find the maximum value in a dictionary.",
    "Write a Python function that removes duplicates from a list while preserving order.",
    "Write a Python function to check if a given number is prime.",
    "Write a Python function that converts Celsius to Fahrenheit.",
    "Write a Python function that merges two sorted lists into one sorted list.",
    "Write a Python function to count the frequency of each character in a string.",
    "Write a Python function that finds the second largest number in a list.",
    "Write a Python function to validate if a string is a valid email address using regex.",
    "Write a Python function that generates a list of squares for numbers 1 to n.",
    "Write a Python function to compute the greatest common divisor (GCD) of two numbers.",
    "Write a Python function that checks if two strings are anagrams.",
    "Write a Python function to flatten a nested list.",
    "Write a Python function that generates a random password of length n.",
    "Write a Python function to calculate the mean, median, and mode of a list.",
    "Write a Python function that simulates a simple dice roll.",
    "Write a Python function to convert a decimal number to binary.",
    "Write a Python function that prints a right-angled triangle of stars.",
    "Write a Python function to find the intersection of two sets.",
    "Write a Python class representing a simple Bank Account with deposit and withdraw methods.",
    "Write a Python function that reads a CSV file and prints the header row.",
    "Write a Python function to calculate the distance between two points in 2D space.",
    "Write a Python function that capitalizes the first letter of every word in a string.",
    "Write a Python function to find the longest word in a sentence.",
    "Write a Python function that shifts all elements of a list to the left by k positions.",
    "Write a Python function to check if a year is a leap year.",
    "Write a Python function that calculates the area of a circle given its radius.",
    "Write a Python function to write a list of strings to a file, one per line.",
    "Write a Python function that implements binary search on a sorted list.",
    "Write a Python function to count the number of vowels in a string.",
    "Write a Python function that transposes a 2D matrix (list of lists).",
    "Write a Python function to find the missing number in a sequence from 1 to n.",
    "Write a Python function that implements a simple Caesar cipher shift.",
    "Write a Python function to check if a list is sorted in ascending order.",
    "Write a Python function that converts a list of tuples into a dictionary.",
    "Write a Python function to find all pairs in a list that sum to a target value.",
    "Write a Python function that parses a JSON string and accesses a specific key.",
    "Write a Python function to calculate the elapsed time of a code block execution.",
    "Write a Python function that strips punctuation from a string.",
    "Write a Python function to find the standard deviation of a list of numbers.",
]
# Combine into a single mapping for Phase 1
PHASE1_FAMILIES = {
    "general_qa": PROMPTS_GENERAL_QA_NEUTRAL,
    "gsm8k_math": PROMPTS_GSM8K_STYLE_NEUTRAL,
    "stories": PROMPTS_STORIES_NEUTRAL,
    "code": PROMPTS_CODE_NEUTRAL,
}

# ---- CS/Lit prompt material for other phases ----

PROMPTS_CS_CORE = [
    "Explain how distributed systems achieve fault tolerance.",
    "How does gradient descent optimize a neural network?",
    "Why do databases use indexing?",
    "What are the trade-offs between strong and eventual consistency?",
    "How do error-correcting codes improve reliability?",
]

PROMPTS_LIT_CORE = [
    "How does literature explore the theme of loneliness?",
    "What makes a character feel psychologically realistic?",
    "How do poets use imagery to convey emotion?",
    "Why do some stories feel timeless across cultures?",
    "How does narrative perspective shape our sympathy for characters?",
]

# At least 25 base questions for CS vs Lit corridor-style work
BASE_QUESTIONS_MANY = [
    "Why do people form communities?",
    "Why do rumors spread so quickly?",
    "Why do some ideas go viral while others die out?",
    "Why do people conform to group opinions?",
    "Why do echo chambers form online?",
    "Why do conspiracy theories persist?",
    "Why do people follow trends?",
    "Why do some narratives dominate public discourse?",
    "Why do political movements rise and fall?",
    "Why do organizations resist change?",
    "Why do new technologies face resistance?",
    "Why do people adopt new tools at different speeds?",
    "Why do some innovations spread globally?",
    "Why do social networks create filter bubbles?",
    "Why do people trust some sources and not others?",
    "Why do certain stories feel universal?",
    "Why do symbols gain cultural power?",
    "Why do myths survive across generations?",
    "Why do people build idols and heroes?",
    "Why do propaganda campaigns succeed or fail?",
    "Why do some books become classics?",
    "Why do certain films become cult favorites?",
    "Why do people form ideological tribes?",
    "Why do revolutions inspire art and literature?",
    "Why do fears about automation keep returning?",
    "Why do people fear being left out?",
    "Why do crises reshape public opinion?",
    "Why do some institutions gain long-term legitimacy?",
    "Why do movements splinter into factions?",
]


def build_cs_prompts_from_bases(bases):
    return [q + "\n" + CS_SUFFIX for q in bases]


def build_lit_prompts_from_bases(bases):
    return [q + "\n" + LIT_SUFFIX for q in bases]


def build_neutral_prompts_from_bases(bases):
    return [q + "\n" + NEUTRAL_SUFFIX for q in bases]
